### ISSUE TITLE
Reason Behind Negative Values of CSI in dB Scale

### ISSUE THREAD

**Issue by asifhanif1122** [dhalperi/linux-80211n-csitool-supplementary#198]
I have read many papers that leveraged CSI to accomplish certain purpose. In all these paper authors plotted CSI in dB scale and it was always positive +ve in value. But values are negative in my case. I receive CSI values  and pass them through _**get_scaled_csi()**_ function. Output of this function is always between 0 and 1. I know that dB function will give negative values when its input is less than 1. But why every paper and even SNR in dB shown by sir D.Halperi on webpage of CSI tool is positive. Can someone throw light on negative values on y-axis.
My CSI plot is displayed below. I didn't have 3rd antenna connected to my NIC so junk values are received on its slot.

Matlab Code Template:

**csi = read_bf_file('myfile.dat');
output= get_scaled_csi(csi) ;
plot(db(abs(squeeze(output).')))
legend('Antenna-1', 'Antenna-2', 'Antenna-3');
xlabel('Sub-carrier Index');
ylabel('SNR (dB)');**  

![snr_1](https://cloud.githubusercontent.com/assets/15953476/16109752/deacba4e-33c3-11e6-8d0d-b92a1155b199.jpg)

**Comment by esoltana** [comment]
I think the error occurred because of the wrong usage of abs function in abs(squeeze(output)). The input in this command is a matrix, you can check how Matlab calculates the magnitude of a matrix to make sure if it's the reason of wrong values. In this case, you need to calculate the magnitude of each complex CSI value separately. So, convert this line to a for loop will solve this problem.
